import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import TopBar from "../../components/shared/TopBar";
import LeftSideBar from "../../components/shared/LeftSideBar";
import RightSideBar from "../../components/shared/RightSideBar";
import BottomBar from "../../components/shared/BottomBar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}bg-black text-white`}>
          <TopBar />
          <main className="flex">
            <LeftSideBar />
            <section className="main-container">
              <div className="w-full">{children}</div>
            </section>
            <RightSideBar />
          </main>
          <BottomBar />
        </body>
      </html>
    </ClerkProvider>
  );
}
